version: '3.7'
services:
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
  
  feature_extractor:
    depends_on:
      - database
    volumes:
    - ./extractor/train:/train
    build: ./extractor
    links: 
      - database